baseURL = "https://blog.kamasaki.net/"
languageCode = "ja-jp"
title = "kamasaki.net"
paginate = 5
defaultContentLanguage = "ja"
hasCJKLanguage = true
# Change it to your Disqus shortname before using
# disqusShortname = "hugo-theme-stack"
