[[main]]
name = "Top"
identifier = "top"
weight = 100
url = "/"
params.icon = "home"

[[main]]
name = "Archives"
identifier = "archives"
weight = 200
url = "/archives"
params.icon = "archives"

[[main]]
name = "Search"
url = "/search"
weight = 300
params.icon = "search"

[[main]]
name = "About"
identifier = "about"
weight = 400
url = "/about"
params.icon = "user"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/kmn4"

[social.params]
icon = "brand-github"
