baseURL = "https://blog.kamasaki.net/"
languageCode = "ja-jp"
theme = "anatole"
title = "kamasaki.net"

[params]
title = "kamasaki.net"
author = "kamasaki"
description = ""
profilePicture = "images/zero.svg"
customCss = ["css/custom.css"]
doNotLoadAnimations = true

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/kmn4"

[[menu.main]]
name = "Top"
identifier = "top"
weight = 100
url = "/"

[[menu.main]]
name = "About"
identifier = "about"
weight = 200
url = "/about"
